spring:
  banner:
    location: additional/banner.txt
  output:
    ansi:
      enabled: ALWAYS
  messages:
    basename: i18n/messages


countOfRightAnswer: 3
main.locale: en
filename: /additional/questions-
fileFormat: .csv