spring:
  banner:
    location: additional/banner.txt
  output:
    ansi:
      enabled: ALWAYS
  messages:
    basename: i18n/messages
  main:
    allow-circular-references: true


countOfRightAnswer: 3
main.locale: ru
filename: /additional/questions-
fileFormat: .csv